from .action_brain import ActionBrain
from .Web_parse import PageParser
from .app_open import AppOpen
from .web_search import WebSearch
from .search_open import SearchOpen
from .win_settings import WinSet
from .windows_manager import WindowsManager
from .Parse_to_text import WordCoordinator
from .excel_manager import ExcelManager
from .presentation_manager import PresentationManager
from .emails import Emails
from .File_manager import FileManager
from .llm_searching import LLMWebSearch
from .tg_mess import TgMessage
from .word_manager import DocumentWorker
from .File_manager import FileDescriptionManager
from . import registry